import type { Scene } from '../lib/weatherCodes'

/**
 * AUTO-GENERATED by `scripts/build-photos.mjs` — do not edit by hand.
 *
 * Lists bundled, commercial-licensed backdrop photos found under
 * `public/photos/<scene>/`. URLs are served as static assets, so the app uses
 * them offline. Empty arrays mean "no local photo for this scene yet" and the
 * caller falls back to a remote source (online build only).
 *
 * Regenerate after adding/removing files: `npm run build:photos`.
 */
export const LOCAL_SCENE_PHOTOS: Record<Scene, string[]> = {
  'clear-day': [],
  'clear-night': [],
  cloudy: [],
  fog: [],
  rain: [],
  thunder: [],
  snow: [],
}

/** Flat pool of every bundled photo, for the rotating photo tile. */
export const LOCAL_PHOTO_POOL: string[] = []
