#!/usr/bin/env node
// Scan public/photos/<scene>/ for bundled backdrop images and regenerate
// src/background/photoManifest.ts so the kiosk can use them offline.
//
//   npm run build:photos
//
// Drop commercial-licensed images (jpg/jpeg/png/webp/avif) into the per-scene
// folders, then run this. Scenes match the app's Scene type.
import { readdirSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SCENES = ['clear-day', 'clear-night', 'cloudy', 'fog', 'rain', 'thunder', 'snow']
const IMG = /\.(jpe?g|png|webp|avif)$/i
const photoDir = 'public/photos'
const outFile = 'src/background/photoManifest.ts'

const perScene = {}
const pool = []
for (const scene of SCENES) {
  const dir = join(photoDir, scene)
  if (!existsSync(dir)) { mkdirSync(dir, { recursive: true }); perScene[scene] = []; continue }
  const files = readdirSync(dir).filter((f) => IMG.test(f)).sort()
  const urls = files.map((f) => `/photos/${scene}/${f}`)
  perScene[scene] = urls
  pool.push(...urls)
}

const sceneEntries = SCENES.map((s) => {
  const key = /[^a-z]/.test(s) ? `'${s}'` : s
  const list = perScene[s].map((u) => `    '${u}',`).join('\n')
  return `  ${key}: [${list ? `\n${list}\n  ` : ''}],`
}).join('\n')

const body = `import type { Scene } from '../lib/weatherCodes'

/**
 * AUTO-GENERATED by \`scripts/build-photos.mjs\` — do not edit by hand.
 *
 * Lists bundled, commercial-licensed backdrop photos found under
 * \`public/photos/<scene>/\`. URLs are served as static assets, so the app uses
 * them offline. Empty arrays mean "no local photo for this scene yet" and the
 * caller falls back to a remote source (online build only).
 *
 * Regenerate after adding/removing files: \`npm run build:photos\`.
 */
export const LOCAL_SCENE_PHOTOS: Record<Scene, string[]> = {
${sceneEntries}
}

/** Flat pool of every bundled photo, for the rotating photo tile. */
export const LOCAL_PHOTO_POOL: string[] = [${pool.length ? `\n${pool.map((u) => `  '${u}',`).join('\n')}\n` : ''}]
`

if (!existsSync('src/background')) mkdirSync('src/background', { recursive: true })
writeFileSync(outFile, body)
console.log(`Wrote ${outFile}: ${pool.length} photo(s) across ${SCENES.length} scenes`)
for (const s of SCENES) console.log(`  ${s}: ${perScene[s].length}`)
